### ISSUE TITLE
Background sound doesn't stop

### ISSUE THREAD

**Issue by yoori85** [suwalszczyzna/MadTadpoles#13]
sound doesn't stop after leaving the app in some cases.

to verify all the cases when the service should be be stopped.

**Comment by NarcyzB** [comment]
the sound doesn't stop after turning off the whole application - as on the attached graphics

![przechwytywaniek](https://user-images.githubusercontent.com/33101796/34295562-44319444-e70e-11e7-8496-977cfe657928.JPG)

**Comment by suwalszczyzna** [comment]
Music is start playing randomly - even though app is closed like above :)

**Comment by yoori85** [comment]
fixed
